version: '3'
services:
  # http://localhost:8080
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app

  # http://localhost:3000
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server